begin;
select plan(24);
select has_table('public','profiles','profiles exists');
select has_table('public','learner_profiles','learner profiles exists');
select has_table('public','schools','schools exists');
select has_table('public','cohorts','cohorts exists');
select has_table('public','cohort_enrolments','cohort enrolments exists');
select has_table('public','lesson_progress','lesson progress exists');
select has_table('public','prompt_responses','prompt responses exists');
select has_table('public','portfolio_artifacts','portfolio artifacts exists');
select has_table('public','portfolio_evidence','portfolio evidence exists');
select has_table('public','curriculum_releases','curriculum releases exists');
select has_table('public','assessment_attempts','assessment attempts exists');
select has_table('public','evidence_records','evidence records exists');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='prompt_responses'),'prompt responses RLS');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='evidence_records'),'evidence records RLS');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='assessment_attempts'),'assessment attempts RLS');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='audit_events'),'audit events RLS');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='prompt_responses' and policyname='prompt_responses_select'),'prompt response select policy');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='prompt_responses' and policyname='prompt_responses_update_own'),'prompt response update policy');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='evidence_records' and policyname='learner or assigned staff reads evidence'),'evidence scoped read policy');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='evidence_reviews' and policyname='assigned staff creates review'),'staff review insert policy');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='assessment_attempts' and policyname='assessment attempts select'),'assessment scoped read policy');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='prompt_responses_release_key_unique'),'stable response release uniqueness');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='lesson_progress_release_unit_unique'),'stable progress release uniqueness');
select ok(not exists(select 1 from information_schema.role_table_grants where table_schema='public' and table_name='audit_events' and grantee in ('anon','authenticated') and privilege_type in ('SELECT','INSERT','UPDATE','DELETE')),'audit events have no client grants');
select ok(exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and p.proname='can_review_learner'),'review authorization helper exists');
select * from finish();
rollback;